/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.SanPham;
import Repository.SanPhamRepository;
import ServiceITF.SanPhamITF;
import ServiceIplm.SanPhamIplm;
import ViewModels.ChatLieuView;
import ViewModels.DanhMucViews;
import ViewModels.MauView;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FormSanPham extends javax.swing.JFrame {

    /**
     * Creates new form FormSanPham
     */
    public FormSanPham() {
        initComponents();
        setLocationRelativeTo(null);
        loadCbMau(service.getListMauSac());
        loadCbSize(service.getListSize());
        loadCbDM(service.getListDanhMuc());
        loadCbCL(service.getListChatLieu());
        loadCbKD(service.getListKieuDang());;      
        loadTable(service.getListSanPham());
    }
    private DefaultComboBoxModel cbmodel;
    private DefaultTableModel tbmodel;
    private SanPhamITF service = new SanPhamIplm();

    public void loadTable(ArrayList<SanPham> list) {
        tbmodel = (DefaultTableModel) tbThongTinSanPham.getModel();
        tbmodel.setRowCount(0);
        tbmodel.setColumnIdentifiers(new String[]{"Mã Sản Phẩm", "Mã Cửa Hàng", "Mã NCC", "Tên Sản Phẩm",
            "Danh Mục", "Màu Sắc", "Size", "Chất Liệu", "Kiểu Dáng",
            "NSX", "Giá Nhập", "Giá Bán", "Số Lượng", "Tình Trạng"});
        for (SanPham x : list) {
            tbmodel.addRow(new Object[]{x.getMaSP(), x.getMaCH(), x.getMaNCC(), x.getTenSP(), x.getTenDanhMuc(),
                x.getTenMau(), x.getTenSize(), x.getTenChatLieu(), x.getTenKieuDang(),
                x.getNgaySX(), x.getGiaNhap(), x.getGiaBan(), x.getSoLuong(), x.htTrangThai()});
        }
    }

    public void loadCbDM(ArrayList<String> listDM) {
        cbDanhMuc.removeAllItems();
        cbLocDanhMuc.removeAllItems();
        cbLocDanhMuc.addItem("Tất Cả");
        for (String x : listDM) {
            cbDanhMuc.addItem(x);
            cbLocDanhMuc.addItem(x);
        }
    }

    public void loadCbMau(ArrayList<String> listMau) {
        cbMauSac.removeAllItems();
        cbLocMau.removeAllItems();
        cbLocMau.addItem("Tất Cả");
        for (String x : listMau) {
            cbMauSac.addItem(x);
            cbLocMau.addItem(x);
        }
    }

    public void loadCbSize(ArrayList<String> listSize) {
        cbSize.removeAllItems();
        cbLocSize.removeAllItems();
        cbLocSize.addItem("Tất Cả");
        for (String x : listSize) {
            cbSize.addItem(x);
            cbLocSize.addItem(x);
        }
    }

    public void loadCbCL(ArrayList<String> listCL) {
        cbChatLieu.removeAllItems();
        cbLocChatLieu.removeAllItems();
        cbLocChatLieu.addItem("Tất Cả");
        for (String x : listCL) {
            cbChatLieu.addItem(x);
            cbLocChatLieu.addItem(x);
        }
    }

    public void loadCbKD(ArrayList<String> listKD) {
        cbKieuDang.removeAllItems();
        cbLocKieuDang.removeAllItems();
        cbLocKieuDang.addItem("Tất Cả");
        for (String x : listKD) {
            cbKieuDang.addItem(x);
            cbLocKieuDang.addItem(x);
        }
    }

    public boolean checkTrung(String ma) {
        for (SanPham a : service.getListSanPham()) {
            if (ma.equals(a.getMaSP())) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btSanPham = new javax.swing.JButton();
        btBanHang = new javax.swing.JButton();
        btNhanVien = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btKhachHang = new javax.swing.JButton();
        btCuaHang = new javax.swing.JButton();
        btNhaCungCap = new javax.swing.JButton();
        btDoiMatKhau = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbThongTinSanPham = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        cbLocSize = new javax.swing.JComboBox<>();
        cbLocMau = new javax.swing.JComboBox<>();
        btTimKiem = new javax.swing.JButton();
        cbLocDanhMuc = new javax.swing.JComboBox<>();
        cbLocKieuDang = new javax.swing.JComboBox<>();
        cbLocChatLieu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaCH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgaySX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btLamMoi = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        cbMauSac = new javax.swing.JComboBox<>();
        cbSize = new javax.swing.JComboBox<>();
        cbChatLieu = new javax.swing.JComboBox<>();
        cbDanhMuc = new javax.swing.JComboBox<>();
        cbKieuDang = new javax.swing.JComboBox<>();
        btThemDanhMuc = new javax.swing.JButton();
        btThemKieuDang = new javax.swing.JButton();
        btThemMauSac = new javax.swing.JButton();
        btThemSize = new javax.swing.JButton();
        btThemChatLieu = new javax.swing.JButton();
        txtMaSP = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btSanPham.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSanPham.setText("SẢN PHẨM");

        btBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btBanHang.setText("BÁN HÀNG");
        btBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanHangActionPerformed(evt);
            }
        });

        btNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNhanVien.setText("NHÂN VIÊN");
        btNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienActionPerformed(evt);
            }
        });

        btHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btHoaDon.setText("HÓA ĐƠN");
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });

        btKhachHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btKhachHang.setText("KHÁCH HÀNG");
        btKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKhachHangActionPerformed(evt);
            }
        });

        btCuaHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCuaHang.setText("CỬA HÀNG");
        btCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuaHangActionPerformed(evt);
            }
        });

        btNhaCungCap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNhaCungCap.setText("NHÀ CUNG CẤP");
        btNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhaCungCapActionPerformed(evt);
            }
        });

        btDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        btDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoiMatKhauActionPerformed(evt);
            }
        });

        btDangXuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDangXuat.setText("ĐĂNG XUẤT");
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBanHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCuaHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNhaCungCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã Sản Phẩm:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbThongTinSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbThongTinSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbThongTinSanPham);

        cbLocSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocSizeActionPerformed(evt);
            }
        });

        cbLocMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocMauActionPerformed(evt);
            }
        });

        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        cbLocDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocDanhMucActionPerformed(evt);
            }
        });

        cbLocKieuDang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocKieuDang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocKieuDangActionPerformed(evt);
            }
        });

        cbLocChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocChatLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cbLocMau, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLocSize, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLocDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLocChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbLocKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTimKiem)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLocMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbLocSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLocDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLocChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLocKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btTimKiem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Cửa Hàng:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã NCC:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Danh Mục:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kiểu Dáng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số Lượng:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tên Sản Phẩm:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày Sản Xuất:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Màu Sắc:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Size:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Chất Liệu:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Giá Nhập:");

        btThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThem.setText("Thêm");
        btThem.setPreferredSize(new java.awt.Dimension(87, 25));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setMaximumSize(new java.awt.Dimension(87, 25));
        btXoa.setMinimumSize(new java.awt.Dimension(87, 25));
        btXoa.setPreferredSize(new java.awt.Dimension(87, 25));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSua.setText("Sửa");
        btSua.setPreferredSize(new java.awt.Dimension(87, 25));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btLamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLamMoi.setText("Làm Mới");
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Trạng Thái:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Giá Bán:");

        cbMauSac.setMaximumRowCount(20);

        cbSize.setMaximumRowCount(20);

        cbChatLieu.setMaximumRowCount(20);

        cbDanhMuc.setMaximumRowCount(20);

        cbKieuDang.setMaximumRowCount(20);

        btThemDanhMuc.setText("+");
        btThemDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDanhMucActionPerformed(evt);
            }
        });

        btThemKieuDang.setText("+");
        btThemKieuDang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemKieuDangActionPerformed(evt);
            }
        });

        btThemMauSac.setText("+");
        btThemMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMauSacActionPerformed(evt);
            }
        });

        btThemSize.setText("+");
        btThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemSizeActionPerformed(evt);
            }
        });

        btThemChatLieu.setText("+");
        btThemChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemChatLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtMaCH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbKieuDang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btThemDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btThemKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtGiaBan)
                                        .addComponent(txtNgaySX)
                                        .addComponent(txtGiaNhap)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cbChatLieu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btThemMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(btLamMoi)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel13)))
                        .addGap(564, 564, 564)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btThemMauSac))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(btThemSize))
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btThemDanhMuc))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel5)
                        .addComponent(cbKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btThemKieuDang))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btThemChatLieu)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLamMoi))
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        SanPham x = new SanPham();
        x.setMaSP(txtMaSP.getText());
        x.setMaCH(txtMaCH.getText());
        x.setMaNCC(txtMaNCC.getText());
        x.setTenMau(cbMauSac.getSelectedItem().toString());
        x.setTenSize(cbSize.getSelectedItem().toString());
        x.setTenDanhMuc(cbDanhMuc.getSelectedItem().toString());
        x.setTenChatLieu(cbChatLieu.getSelectedItem().toString());
        x.setTenKieuDang(cbKieuDang.getSelectedItem().toString());
        x.setTenSP(txtTenSP.getText());
        x.setNgaySX(txtNgaySX.getText());
        x.setGiaNhap(Integer.parseInt(txtGiaNhap.getText()));
        x.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
        x.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

        try {
            if (txtMaSP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Sản Phẩm");
                return;
            }
            for (SanPham a : service.getListSanPham()) {
                if (txtMaSP.getText().equals(a.getMaSP())) {
                    JOptionPane.showMessageDialog(this, "Thêm không thành công do mã sản phẩm đã tồn tại");
                    return;
                }
            }
            if (txtMaCH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Cửa Hàng");
                return;
            }
            if (txtMaNCC.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Nhà Cung Cấp");
                return;
            }
            if (txtTenSP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Tên Sản Phẩm");
                return;
            }
            if (txtNgaySX.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Ngày Sản Xuất");
                return;
            }
            if (txtGiaNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Giá Nhập");
                return;
            }
            if (txtGiaBan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Giá Bán");
                return;
            }
            if (txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Số Lượng");
                return;
            }
            if (service.them(x)) {
                loadTable(service.getListSanPham());
                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        String ma = txtMaSP.getText();
        SanPham x = new SanPham();
        x.setMaCH(txtMaCH.getText());
        x.setMaNCC(txtMaNCC.getText());
        x.setTenMau(cbMauSac.getSelectedItem().toString());
        x.setTenSize(cbSize.getSelectedItem().toString());
        x.setTenDanhMuc(cbDanhMuc.getSelectedItem().toString());
        x.setTenChatLieu(cbChatLieu.getSelectedItem().toString());
        x.setTenKieuDang(cbKieuDang.getSelectedItem().toString());
        x.setTenSP(txtTenSP.getText());
        x.setNgaySX(txtNgaySX.getText());
        x.setGiaNhap(Integer.parseInt(txtGiaNhap.getText()));
        x.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
        x.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

        try {
            if (txtMaSP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Sản Phẩm");
                return;
            }
            if (checkTrung(txtMaSP.getText()) == false) {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại do bạn mã sản phẩm không tồn tại");
                return;
            }

            if (txtMaCH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Cửa Hàng");
                return;
            }
            if (txtMaNCC.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Mã Nhà Cung Cấp");
                return;
            }
            if (txtTenSP.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Tên Sản Phẩm");
                return;
            }
            if (txtNgaySX.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Ngày Sản Xuất");
                return;
            }
            if (txtGiaNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Giá Nhập");
                return;
            }
            if (txtGiaBan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Giá Bán");
                return;
            }
            if (txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Số Lượng");
                return;
            }
            if (service.sua(x, ma)) {
                loadTable(service.getListSanPham());
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String ma = txtMaSP.getText();
        try {
            if (ma.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Xóa Thất Bại do bạn chưa nhập mã sản phẩm.");
                return;
            }
            if (checkTrung(ma) == false) {
                JOptionPane.showMessageDialog(this, "Xóa Thất Bại do bạn mã sản phẩm không tồn tại");
                return;
            }
            if (service.xoa(ma)) {
                JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa Sản Phẩm này không?");
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
                loadTable(service.getListSanPham());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa không thành công");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaSP.setText("");
        txtMaCH.setText("");
        txtMaNCC.setText("");
        cbMauSac.setSelectedIndex(0);
        cbSize.setSelectedIndex(0);
        cbDanhMuc.setSelectedIndex(0);
        cbChatLieu.setSelectedIndex(0);
        cbKieuDang.setSelectedIndex(0);
        txtTenSP.setText("");
        txtNgaySX.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        txtSoLuong.setText("");
        txtTrangThai.setText("");
        loadTable(service.getListSanPham());
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void tbThongTinSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tbThongTinSanPham.getSelectedRow();
        txtMaSP.setText(tbThongTinSanPham.getValueAt(row, 0).toString());
        txtMaCH.setText(tbThongTinSanPham.getValueAt(row, 1).toString());
        txtMaNCC.setText(tbThongTinSanPham.getValueAt(row, 2).toString());
        txtTenSP.setText(tbThongTinSanPham.getValueAt(row, 3).toString());
        cbDanhMuc.setSelectedItem(tbThongTinSanPham.getValueAt(row, 4));
        cbMauSac.setSelectedItem(tbThongTinSanPham.getValueAt(row, 5));
        cbSize.setSelectedItem(tbThongTinSanPham.getValueAt(row, 6));
        cbChatLieu.setSelectedItem(tbThongTinSanPham.getValueAt(row, 7));
        cbKieuDang.setSelectedItem(tbThongTinSanPham.getValueAt(row, 8));
        txtNgaySX.setText(tbThongTinSanPham.getValueAt(row, 9).toString());
        txtGiaNhap.setText(tbThongTinSanPham.getValueAt(row, 10).toString());
        txtGiaBan.setText(tbThongTinSanPham.getValueAt(row, 11).toString());
        txtSoLuong.setText(tbThongTinSanPham.getValueAt(row, 12).toString());
        txtTrangThai.setText(tbThongTinSanPham.getValueAt(row, 13).toString());
    }//GEN-LAST:event_tbThongTinSanPhamMouseClicked

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String ma = txtTimKiem.getText();
        String mau = cbLocMau.getSelectedItem().toString();
        String size = cbLocSize.getSelectedItem().toString();
        String dm = cbLocDanhMuc.getSelectedItem().toString();
        String cl = cbLocChatLieu.getSelectedItem().toString();
        String kd = cbLocKieuDang.getSelectedItem().toString();
        System.out.println("aaaaaaaaaaaaaa "+mau);
        System.out.println("aaaaaaaaaaaaaa "+size);
        System.out.println("aaaaaaaaaaaaaa "+dm);
        System.out.println("aaaaaaaaaaaaaa "+cl);
        System.out.println("aaaaaaaaaaaaaa "+kd);
        SanPhamRepository x=new SanPhamRepository();
        try {
            if (ma.isEmpty()) {               
                loadTable(x.getListLoc(mau, size, dm, cl, kd));
                if (tbThongTinSanPham.getRowCount()==0) {
                    JOptionPane.showMessageDialog(this, "Không có Sản Phẩm phù hợp");
                }
                return;
            }
            loadTable(service.tim(ma));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void cbLocMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocMauActionPerformed
        // TODO add your handling code here:
        /*String mau = (String) cbLocMau.getSelectedItem();
        String size = (String) cbLocSize.getSelectedItem();
        String dm = (String) cbDanhMuc.getSelectedItem();
        String cl = (String) cbLocChatLieu.getSelectedItem();
        String kd = (String) cbKieuDang.getSelectedItem();
        try {
            loadTable(service.getListLoc(mau, size, dm, cl, kd));
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cbLocMauActionPerformed

    private void cbLocSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocSizeActionPerformed
        // TODO add your handling code here:
        /*String mau = (String) cbLocMau.getSelectedItem();
        String size = (String) cbLocSize.getSelectedItem();
        String dm = (String) cbDanhMuc.getSelectedItem();
        String cl = (String) cbLocChatLieu.getSelectedItem();
        String kd = (String) cbKieuDang.getSelectedItem();
        try {
            loadTable(service.getListLoc(mau, size, dm, cl, kd));
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cbLocSizeActionPerformed

    private void btBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanHangActionPerformed
        // TODO add your handling code here:
        FormBanHang x = new FormBanHang();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btBanHangActionPerformed

    private void btThemDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDanhMucActionPerformed
        // TODO add your handling code here:
        FormDanhMuc x = new FormDanhMuc(this, true);
        x.setVisible(true);
        loadCbDM(service.getListDanhMuc());
        cbDanhMuc.setSelectedItem(x.getTen());
    }//GEN-LAST:event_btThemDanhMucActionPerformed

    private void btThemChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemChatLieuActionPerformed
        // TODO add your handling code here:
        ChatLieu x = new ChatLieu(this, true);
        x.setVisible(true);
        loadCbCL(service.getListChatLieu());
        cbChatLieu.setSelectedItem(x.getTen());
    }//GEN-LAST:event_btThemChatLieuActionPerformed

    private void btThemMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMauSacActionPerformed
        // TODO add your handling code here:
        Mau x = new Mau(this, true);
        x.setVisible(true);
        loadCbMau(service.getListMauSac());
        cbMauSac.setSelectedItem(x.getTen());
    }//GEN-LAST:event_btThemMauSacActionPerformed

    private void btThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemSizeActionPerformed
        // TODO add your handling code here:
        Size x = new Size(this, true);
        x.setVisible(true);
        loadCbSize(service.getListSize());
        cbSize.setSelectedItem(x.getTen());
    }//GEN-LAST:event_btThemSizeActionPerformed

    private void btThemKieuDangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemKieuDangActionPerformed
        // TODO add your handling code here:
        FormKieuDang x = new FormKieuDang(this, true);
        x.setVisible(true);
        loadCbKD(service.getListKieuDang());
        cbKieuDang.setSelectedItem(x.getTen());
    }//GEN-LAST:event_btThemKieuDangActionPerformed

    private void cbLocDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocDanhMucActionPerformed
        // TODO add your handling code here:
        /*String mau = (String) cbLocMau.getSelectedItem();
        String size = (String) cbLocSize.getSelectedItem();
        String dm = (String) cbDanhMuc.getSelectedItem();
        String cl = (String) cbLocChatLieu.getSelectedItem();
        String kd = (String) cbKieuDang.getSelectedItem();
        try {
            loadTable(service.getListLoc(mau, size, dm, cl, kd));
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cbLocDanhMucActionPerformed

    private void cbLocKieuDangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocKieuDangActionPerformed
        // TODO add your handling code here:
        /*String mau = (String) cbLocMau.getSelectedItem();
        String size = (String) cbLocSize.getSelectedItem();
        String dm = (String) cbDanhMuc.getSelectedItem();
        String cl = (String) cbLocChatLieu.getSelectedItem();
        String kd = (String) cbKieuDang.getSelectedItem();
        try {
            loadTable(service.getListLoc(mau, size, dm, cl, kd));
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cbLocKieuDangActionPerformed

    private void cbLocChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocChatLieuActionPerformed
        // TODO add your handling code here:
        /*String mau = (String) cbLocMau.getSelectedItem();
        String size = (String) cbLocSize.getSelectedItem();
        String dm = (String) cbDanhMuc.getSelectedItem();
        String cl = (String) cbLocChatLieu.getSelectedItem();
        String kd = (String) cbKieuDang.getSelectedItem();
        try {
            loadTable(service.getListLoc(mau, size, dm, cl, kd));
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cbLocChatLieuActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        // TODO add your handling code here:
        FormHoaDon x = new FormHoaDon();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienActionPerformed
        // TODO add your handling code here:
        FormNhanVien x = new FormNhanVien();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btNhanVienActionPerformed

    private void btCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuaHangActionPerformed
        // TODO add your handling code here:
        FormCuaHang x = new FormCuaHang();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCuaHangActionPerformed

    private void btNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhaCungCapActionPerformed
        // TODO add your handling code here:
        FormNhaCungCap x = new FormNhaCungCap();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btNhaCungCapActionPerformed

    private void btKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKhachHangActionPerformed
        // TODO add your handling code here:
        FormKhachHang x = new FormKhachHang();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btKhachHangActionPerformed

    private void btDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiMatKhauActionPerformed
        // TODO add your handling code here:
        FormDoiMatKhau x = new FormDoiMatKhau();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btDoiMatKhauActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap x = new DangNhap();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanHang;
    private javax.swing.JButton btCuaHang;
    private javax.swing.JButton btDangXuat;
    private javax.swing.JButton btDoiMatKhau;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btKhachHang;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btNhaCungCap;
    private javax.swing.JButton btNhanVien;
    private javax.swing.JButton btSanPham;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemChatLieu;
    private javax.swing.JButton btThemDanhMuc;
    private javax.swing.JButton btThemKieuDang;
    private javax.swing.JButton btThemMauSac;
    private javax.swing.JButton btThemSize;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbChatLieu;
    private javax.swing.JComboBox<String> cbDanhMuc;
    private javax.swing.JComboBox<String> cbKieuDang;
    private javax.swing.JComboBox<String> cbLocChatLieu;
    private javax.swing.JComboBox<String> cbLocDanhMuc;
    private javax.swing.JComboBox<String> cbLocKieuDang;
    private javax.swing.JComboBox<String> cbLocMau;
    private javax.swing.JComboBox<String> cbLocSize;
    private javax.swing.JComboBox<String> cbMauSac;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbThongTinSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaCH;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNgaySX;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
